# Scratch

In [57]:
%load_ext autoreload
%autoreload 2

import json
import math

import torch
from transformers import BertTokenizer,BertModel
import numpy as np

import data
import config
import model

np.set_printoptions(suppress=True)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [62]:
trainloader = data.get_loader(train=True)
trainloader

In [69]:
for i, batch in enumerate(trainloader):
    print(f"Batch {i}")
    print(len(batch))
    print(len(batch[0]))
    print(batch[0].size())
    #print(batch)

Batch 0
5
128
torch.Size([128, 2048, 14, 14])
Batch 1
5
34
torch.Size([34, 2048, 14, 14])


In [70]:
20000 * 3 * 18

1080000

In [58]:
# Prepare toy data

# with open(config.QUESTIONS_TEST_FILEPATH, 'r') as fd:
#     questions_json = json.load(fd)
# with open(config.ANNOTATIONS_VAL_FILEPATH, 'r') as fd:
#     answers_json = json.load(fd)

# # copy over
# questions_json_copy = dict()
# questions_json_copy["info"] = questions_json["info"]
# questions_json_copy["task_type"] = questions_json["task_type"]
# questions_json_copy["data_type"] = questions_json["data_type"]
# questions_json_copy["license"] = questions_json["license"]
# questions_json_copy["data_subtype"] = questions_json["data_subtype"]
# questions_json_copy["num_choices"] = questions_json["num_choices"]
# questions_json_copy["questions"] = []
# for questions_json_i in questions_json["questions"]:
#     if questions_json_i["image_id"] in [30000, 30001, 30002]:
#         questions_json_copy["questions"].append(questions_json_i)
# # save
# with open("toy/Questions/Questions_Test_abstract_v002/MultipleChoice_abstract_v002_test2015_questions.json", 'w') as f:
#     json.dump(questions_json_copy, f, ensure_ascii=False)


# # copy over
# answers_json_copy = dict()
# answers_json_copy["info"] = answers_json["info"]
# answers_json_copy["data_type"] = answers_json["data_type"]
# answers_json_copy["license"] = answers_json["license"]
# answers_json_copy["data_subtype"] = answers_json["data_subtype"]
# answers_json_copy["annotations"] = []
# for answers_json_i in answers_json["annotations"]:
#     if answers_json_i["image_id"] in [20000, 20001, 20002]:
#         answers_json_copy["annotations"].append(answers_json_i)

# # save
# with open("toy/Annotations/abstract_v002_val2015_annotations.json", 'w') as f:
#    json.dump(answers_json_copy, f, ensure_ascii=False)

In [87]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
pretrained_model = BertModel.from_pretrained("bert-base-uncased")

In [122]:
sentences = [
    'What color is the ladies pants?', 
    'How is the equipments with bars called?', 
    'Is the woman on the couch sporting white hair?'
]
choices = [
    "blue", 
    "slides", 
    "yes", 
]

v = torch.rand(3, 2048, 14, 14)

# wrapped_input = tokenizer(
#     sentences, 
#     max_length=15, 
#     add_special_tokens=True, 
#     truncation=True, 
#     padding='max_length', 
#     return_tensors="pt"
# )
wrapped_input = tokenizer(
    text=sentences, 
    text_pair=choices, 
    add_special_tokens=True, 
    truncation=False, 
    padding=True, 
    return_tensors="pt"
)

print(wrapped_input)
net = model.SimpleNet(pretrained_model)
output = net(v, wrapped_input)
output

{'input_ids': tensor([[  101,  2054,  3609,  2003,  1996,  6456,  6471,  1029,   102,  2630,
           102,     0,     0,     0],
        [  101,  2129,  2003,  1996,  3941,  2015,  2007,  6963,  2170,  1029,
           102, 14816,   102,     0],
        [  101,  2003,  1996,  2450,  2006,  1996,  6411,  7419,  2317,  2606,
          1029,   102,  2748,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}


tensor([[0.4444],
        [0.3974],
        [0.4640]], grad_fn=<SigmoidBackward0>)

In [ ]:
{
'input_ids': 
    tensor([[ 101, 2054, 3609, 2003, 1996, 6456, 6471, 1029,  102,    0,    0,    0, 0,    0,    0],
            [ 101, 2129, 2003, 1996, 3941, 2015, 2007, 6963, 2170, 1029,  102,    0,0,    0,    0],
            [ 101, 2003, 1996, 2450, 2006, 1996, 6411, 7419, 2317, 2606, 1029,  102,0,    0,    0]]), 
'token_type_ids': 
    tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 
'attention_mask': 
    tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
            [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
            [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]])}

In [78]:
wrapped_input.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])

In [100]:
v = torch.rand(1, 3, 4, 4)
v.norm(p=2, dim=1, keepdim=True).expand_as(v)

tensor([[[[0.9633, 0.5874, 1.6305, 0.8024],
          [0.9662, 0.9120, 1.2231, 1.1069],
          [1.4864, 1.1959, 1.1099, 0.9549],
          [0.8396, 0.8468, 0.9976, 0.9378]],

         [[0.9633, 0.5874, 1.6305, 0.8024],
          [0.9662, 0.9120, 1.2231, 1.1069],
          [1.4864, 1.1959, 1.1099, 0.9549],
          [0.8396, 0.8468, 0.9976, 0.9378]],

         [[0.9633, 0.5874, 1.6305, 0.8024],
          [0.9662, 0.9120, 1.2231, 1.1069],
          [1.4864, 1.1959, 1.1099, 0.9549],
          [0.8396, 0.8468, 0.9976, 0.9378]]]])

In [105]:
math.prod(v.size())

48

In [118]:
with open(config.QUESTIONS_TRAIN_FILEPATH, 'r') as fd:
    questions_json = json.load(fd)
with open(config.ANNOTATIONS_TRAIN_FILEPATH, 'r') as fd:
    answers_json = json.load(fd)

In [7]:
toy_logs = torch.load("logs/toy_2024_04_24_22_38_03_1.pth")
toy_logs.keys()

dict_keys(['filename', 'tracker', 'config', 'weights', 'eval'])

In [8]:
toy_logs["eval"]["preds"]

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.], requires_grad=True)

In [181]:
#a = torch.rand(10).view(-1)
#b = torch.rand(10).view(-1)
#output = torch.Tensor([1, 0, 1, 0, 1])
output = torch.tensor([0, 1, 0, 1, 1])
a = torch.tensor([1, 0, 1, 0, 0])
agree = (a == output).type(torch.IntTensor)
indices_agree = torch.nonzero(a).view(-1) # convert mask to indices
pos_agree = agree[indices_agree]     # accuracy for positive examples only
pos_acc = pos_agree.float().mean()
print(pos_acc)

tensor([0, 0, 0, 0, 0], dtype=torch.int32)
tensor(0.)


In [209]:
import numpy as np
import random
x = list(range(10))
x.pop(0)
x = random.sample(x, k=2)
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


[4, 6]

In [12]:
import h5py
features_file = h5py.File("resnet_train_embeddings.h5", 'r')
features_file["features"][0]

array([[[2.3279e-01, 6.3818e-01, 1.0225e+00, ..., 0.0000e+00,
         0.0000e+00, 0.0000e+00],
        [4.0576e-01, 9.6191e-01, 1.5811e+00, ..., 0.0000e+00,
         0.0000e+00, 0.0000e+00],
        [1.3809e+00, 1.6777e+00, 1.9307e+00, ..., 1.4492e+00,
         4.3774e-01, 8.9172e-02],
        ...,
        [2.9370e-01, 6.8848e-01, 2.6367e+00, ..., 4.3384e-01,
         1.7847e-01, 3.7744e-01],
        [4.3945e-01, 7.2754e-01, 1.5107e+00, ..., 2.9810e-01,
         6.5527e-01, 3.3472e-01],
        [4.4824e-01, 8.2397e-02, 7.8955e-01, ..., 0.0000e+00,
         2.1759e-02, 1.1365e-01]],

       [[0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 3.0212e-02,
         1.9482e-01, 2.3169e-01],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00,
         0.0000e+00, 0.0000e+00],
        [8.4686e-03, 1.6345e-01, 4.1431e-01, ..., 2.6538e-01,
         7.8064e-02, 7.6111e-02],
        ...,
        [0.0000e+00, 1.0901e-01, 3.6377e-01, ..., 1.8066e-01,
         2.9761e-01, 6.5869e-01],
        [3.4

In [22]:
x = torch.rand((32, 512))
x.view(32, 512, 1, 1).shape

torch.Size([32, 512, 1, 1])

In [72]:
attention_logs = torch.load("logs/toy_2024_04_26_20_20_37_1.pth", map_location=torch.device('cpu'))
attention_logs["eval"].keys()

dict_keys(['y_preds_val', 'y_true_val', 'losses_val', 'overall_accs_val', 'pos_accs_val', 'idx_val', 'q_ids_val', 'losses_train', 'overall_accs_train', 'pos_accs_train'])

In [58]:
#[x for x in np.array(attention_logs["eval"]["y_preds"]) if x > 0.5152 or x < 0.5147]
np.array(attention_logs["eval"]["y_preds"][:20])

array([0.9668055 , 0.00073079, 0.00071978, 0.9554876 , 0.0007077 ,
       0.55026925, 0.966619  , 0.00072942, 0.00073408, 0.9668766 ,
       0.00082607, 0.00083701, 0.7499713 , 0.20152688, 0.00378643,
       0.9396422 , 0.00086231, 0.00084142, 0.9273825 , 0.00084333],
      dtype=float32)

In [76]:
attention_logs["eval"]#["overall_accs_train"]

{'y_preds_val': tensor([0.4949, 0.4946, 0.4949, 0.4947, 0.4953, 0.4950, 0.4943, 0.4954, 0.4940,
         0.4977, 0.4975, 0.4980, 0.4985, 0.4976, 0.4993, 0.4984, 0.4973, 0.4982,
         0.4998, 0.5001, 0.5004, 0.5001, 0.5003, 0.5001, 0.5016, 0.5009, 0.5006]),
 'y_true_val': tensor([1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0.,
         1., 0., 0., 1., 0., 0., 1., 0., 0.]),
 'losses_val': [0.4620986580848694],
 'overall_accs_val': [0.5185185074806213],
 'pos_accs_val': [0.2222222238779068],
 'idx_val': tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26]),
 'q_ids_val': tensor([200010, 200010, 200010, 200011, 200011, 200011, 200012, 200012, 200012,
         200020, 200020, 200020, 200021, 200021, 200021, 200022, 200022, 200022,
         200000, 200000, 200000, 200001, 200001, 200001, 200002, 200002, 200002]),
 'losses_train': [0.46085718274116516],
 'overall_accs_train': [0.4814814925193786